# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: nbm modular package

on:
  workflow_call:
      
inputs:
  nb_release_version:
    required: true
    type: string
  nb-meta-inf:
    required: true
    type: string
  NB_VERSION_NR:
    required: true
    type: string
  NB_RELEASE_LABEL:
    required: true
    type: string
  release_tag_version:
    required: true
    type: string
  NB_PRERELEASE:
    required: true
    type: boolean
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - run: echo "::set-output name=NB_META_INF::${{ INPUT_NB-META-INF }}"
    - run: echo "::set-output name=RELEASE_TAG_VERSION::${{ INPUT_RELEASE_TAG_VERSION }}"
    - name : get version
      run: echo "::set-output name=version::$(grep 'OpenIDE-Module-Specification-Version'  ./manifest.mf | cut -d':' -f 2-)"
      id: nbm_version
    - name: view version
      run: echo ${{ steps.nbm_version.outputs.version }}  
    - name : prepare the files from project
      run : mkdir -p  nb-plugin-package/src/main/java
    - name : prepare the files from project  
      run : mkdir -p nb-plugin-package/src/main/nbm
    - name : prepare the files from project  
      run : mkdir -p nb-plugin-package/src/main/resources/org/netbeans/modules/php/laravel
    - name : copy main app java
      run : cp -rf ./src/org nb-plugin-package/src/main/java
    - name : copy base resources
      run : cp -rf ./src/org/netbeans/modules/php/laravel/resources nb-plugin-package/src/main/resources/org/netbeans/modules/php/laravel
    - name : create ui bundle resource 
      run : mkdir -p nb-plugin-package/src/main/resources/org/netbeans/modules/php/laravel/ui/customizer
    - name : copy bundle customizer
      run : cp  ./src/org/netbeans/modules/php/laravel/ui/customizer/Bundle.properties nb-plugin-package/src/main/resources/org/netbeans/modules/php/laravel/ui/customizer
    - name : create ui bundle options resource 
      run : mkdir -p nb-plugin-package/src/main/resources/org/netbeans/modules/php/laravel/ui/options
    - name : copy bundle laravel options
      run : cp  ./src/org/netbeans/modules/php/laravel/ui/options/Bundle.properties nb-plugin-package/src/main/resources/org/netbeans/modules/php/laravel/ui/options
    - name : prepare the files from project
      run : cp ./manifest.mf nb-plugin-package/src/main/nbm/manifest.mf
    - name : prepare the files from project  
      run : cp ./.github/pom.xml nb-plugin-package/pom.xml
    - name : prepare the files from project  
      run : cp ./nbproject/project.properties nb-plugin-package/project.properties
    - name : prepare the files from project  
      run : cp ./LICENSE nb-plugin-package/LICENSE
    - name : package nmb ${{ INPUT_NB_VERSION_NR }}
      working-directory: ./nb-plugin-package
      run : mvn package  
    - name : upload nbm ${{ INPUT_NB_VERSION_NR }}
      uses: actions/upload-artifact@v4
      with:
        name: php-laravel-nbm-${{ INPUT_NB_VERSION_NR }}
        path: ./nb-plugin-package/target/nbm/*.nbm        
    - name: {{ INPUT_NB_RELEASE_LABEL }}
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ github.token }}
      id: create_release
      with:
        draft: false
        prerelease: {{ INPUT_NB_PRERELEASE }}
        release_name: Netbeans Blade Php release ${{ steps.nbm_version.outputs.version }}  
        tag_name: nb${{ INPUT_NB_VERSION_NR }}laravel${{ INPUT_RELEASE_TAG_VERSION }}
        body_path: .github/workflows/CHANGELOG.md
    - name: upload nbm artifact
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./nb-plugin-package/target/nbm/php.laravel.framework-1.0.0.nbm
        asset_name: php-laravel${{ INPUT_NB_VERSION_NR }}-${{ steps.nbm_version.outputs.version }}.nbm
        asset_content_type: application/nbm
