# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: nbm package && pre-release 220

on:
  workflow_dispatch:

env:
  NB_RELEASE_VERSION: 220  
  NB_META_INF: 22-0d0bfcf3faf364a2643238f2a44e1bb6eb8217bd
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name : get version
      run: echo "::set-output name=version::$(grep 'OpenIDE-Module-Specification-Version'  ./manifest.mf | cut -d':' -f 2-)"
      id: nbm_version
    - name: view version
      run: echo ${{ steps.nbm_version.outputs.version }}    
    - name : prepare the files from project
      run : mkdir -p  nb-plugin-package/src/main/java
    - name : prepare the files from project  
      run : mkdir -p nb-plugin-package/src/main/nbm
    - name : prepare the files from project  
      run : mkdir -p nb-plugin-package/src/main/resources/org/netbeans/modules/php/laravel
    - name : copy main app java
      run : cp -rf ./src/org nb-plugin-package/src/main/java
    - name : copy base resources
      run : cp -rf ./src/org/netbeans/modules/php/laravel/resources nb-plugin-package/src/main/resources/org/netbeans/modules/php/laravel
    - name : create ui bundle resource 
      run : mkdir -p nb-plugin-package/src/main/resources/org/netbeans/modules/php/laravel/ui/customizer
    - name : copy bundle customizer
      run : cp  ./src/org/netbeans/modules/php/laravel/ui/customizer/Bundle.properties nb-plugin-package/src/main/resources/org/netbeans/modules/php/laravel/ui/customizer
    - name : create ui bundle options resource 
      run : mkdir -p nb-plugin-package/src/main/resources/org/netbeans/modules/php/laravel/ui/options
    - name : copy bundle laravel options
      run : cp  ./src/org/netbeans/modules/php/laravel/ui/options/Bundle.properties nb-plugin-package/src/main/resources/org/netbeans/modules/php/laravel/ui/options
    - name : prepare the files from project
      run : cp ./manifest.mf nb-plugin-package/src/main/nbm/manifest.mf
    - name : prepare the files from project  
      run : cp ./.github/pom.xml nb-plugin-package/pom.xml
    - name : prepare the files from project  
      run : cp ./nbproject/project.properties nb-plugin-package/project.properties
    - name : prepare the files from project  
      run : cp ./LICENSE nb-plugin-package/LICENSE
    - name : package nmb 220
      working-directory: ./nb-plugin-package
      run : mvn package  
    - name : upload nbm 220
      uses: actions/upload-artifact@v4
      with:
        name: php-laravel-nbm-220
        path: ./nb-plugin-package/target/nbm/*.nbm        
    - name: pre-release220
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ github.token }}
      id: create_release
      with:
        draft: false
        prerelease: true
        release_name: Netbeans Blade Php release ${{ steps.nbm_version.outputs.version }}  
        tag_name: nb220laravelv1.0.5
        body_path: .github/workflows/CHANGELOG.md
    - name: upload nbm artifact
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./nb-plugin-package/target/nbm/php.laravel.framework-1.0.6.nbm
        asset_name: php-laravel220-${{ steps.nbm_version.outputs.version }}.nbm
        asset_content_type: application/nbm
