# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: nbm modular pre-release package 220

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/nbm/package.yml
      with:
        NB_RELEASE_VERSION: 220  
        NB_META_INF: 22-0d0bfcf3faf364a2643238f2a44e1bb6eb8217bd
        NB_VERSION_NR: 220
        NB_RELEASE_LABEL: prerelease
        RELEASE_TAG_VERSION: nb220laravelv1.0.7
        NB_PRERELEASE: true
    
