# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: nbm modular pre-release package

on:
  workflow_dispatch:
    inputs:
        tag-version:
            required: true
            type: string
        pre-release:
            required: true
            type: boolean

jobs:
  create_release:
    name: Create pre-release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v3   
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: ${{ inputs.pre-release }}
          release_name: Netbeans Blade Php release all
          tag_name:  ${{ inputs.tag-version }}
          body_path: .github/workflows/CHANGELOG.md
  build:
    needs: create_release 
    strategy:
      matrix:
        label: [23, 24, 25, 26]
        include:
          - label: 23
            version: 23-2985f1fa57ce0c1877bad0f86d5e5504d65f9286
            java: 11
          - label: 24
            version: 24-6308a54f5ac18a75f460d86cc9bb8d4cc7213564
            java: 11
          - label: 25
            version: 25-0f82d968998b78ef4d323537d1149eb68e747d9a
            java: 17
          - label: 26
            version: 26-81d21190648c8a1bae92bc9cdb0bb9783ae4912f
            java: 17  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '${{ matrix.java }}'
        distribution: 'temurin'
    - name : get version
      run: echo "::set-output name=version::$(grep 'OpenIDE-Module-Specification-Version'  ./manifest.mf | cut -d':' -f 2-)"
      id: nbm_version
    - name: Set version
      run: echo ${{ steps.nbm_version.outputs.version }}    
    - name : prepare the files from project
      run : mkdir -p  nb-plugin-package/src/main/java
    - name : prepare the files from project  
      run : mkdir -p nb-plugin-package/src/main/nbm
    - name : prepare the files from project  
      run : mkdir -p nb-plugin-package/src/main/resources/org/netbeans/modules/php/laravel
    - name : copy main app java
      run : cp -rf ./src/org nb-plugin-package/src/main/java
    - name : copy base resources
      run : cp -rf ./src/org/netbeans/modules/php/laravel/resources nb-plugin-package/src/main/resources/org/netbeans/modules/php/laravel
    - name : create ui bundle resource 
      run : mkdir -p nb-plugin-package/src/main/resources/org/netbeans/modules/php/laravel/ui/customizer
    - name : copy bundle customizer
      run : cp  ./src/org/netbeans/modules/php/laravel/ui/customizer/Bundle.properties nb-plugin-package/src/main/resources/org/netbeans/modules/php/laravel/ui/customizer
    - name : create ui bundle options resource 
      run : mkdir -p nb-plugin-package/src/main/resources/org/netbeans/modules/php/laravel/ui/options
    - name : copy bundle laravel options
      run : cp  ./src/org/netbeans/modules/php/laravel/ui/options/Bundle.properties nb-plugin-package/src/main/resources/org/netbeans/modules/php/laravel/ui/options
    - name : prepare the files from project
      run : cp ./manifest.mf nb-plugin-package/src/main/nbm/manifest.mf
    - name : prepare the files from project  
      run : cp ./.github/pom.xml nb-plugin-package/pom.xml
    - name : prepare the files from project  
      run : cp ./nbproject/project.properties nb-plugin-package/project.properties
    - name : prepare the files from project  
      run : cp ./LICENSE nb-plugin-package/LICENSE
    - name : package nbm${{ matrix.label }}
      working-directory: ./nb-plugin-package
      env:
        NB_RELEASE_VERSION: ${{ matrix.label }}0 
        NB_META_INF: ${{ matrix.version }}
      run : echo NB_RELEASE_VERSION | mvn package  
    - name : upload nbm ${{ matrix.label }}
      uses: actions/upload-artifact@v4
      with:
        name: php-laravel-nbm-${{ matrix.label }}
        path: ./nb-plugin-package/target/nbm/*.nbm     
    - name: upload nbm artifact
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./nb-plugin-package/target/nbm/php.laravel.framework-1.0.0.nbm
        asset_name: php-laravel${{ matrix.label }}-${{ steps.nbm_version.outputs.version }}.nbm
        asset_content_type: application/nbm
