# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: nbm modular pre-release package 220

on:
  workflow_dispatch:
    inputs:
      nb-meta-inf:
        required: true
        type: string
      NB_RELEASE_VERSION:
        required: true
        type: string
      NB_VERSION_NR:
        required: true
        type: string
      NB_RELEASE_LABEL:
        required: true
        type: string
      RELEASE_TAG_VERSION:
        required: true
        type: string
      NB_PRERELEASE:
        required: true
        type: boolean

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/actions/nbm-modular-package
      with:
        nb-meta-inf: 22-0d0bfcf3faf364a2643238f2a44e1bb6eb8217bd
        NB_RELEASE_VERSION: 220  
        NB_VERSION_NR: 220
        NB_RELEASE_LABEL: prerelease
        RELEASE_TAG_VERSION: nb220laravelv1.0.7
        NB_PRERELEASE: true
    
